steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE}/${_SERVICE}:${SHORT_SHA}', '.' ]
    id: 'Build Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE}/${_SERVICE}:${SHORT_SHA}']
    id: 'Push Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_SECRET_SERVICE}/${_SECRET_SERVICE}:${SHORT_SHA}', '-f', '-f Dockerfile.secrets', '.' ]
    id: 'Build Secret Service Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_SECRET_SERVICE}/${_SECRET_SERVICE}:${SHORT_SHA}' ]
    id: 'Push Secret Service Docker Image'

  - name: 'google/cloud-sdk:latest'
    entrypoint: 'sh'
    args:
      - -xe
      - -c
      - |
        gcloud deploy apply --file deploy/pipeline.yml --region=asia-southeast2
        gcloud deploy apply --file deploy/dev.yml --region=asia-southeast2
        gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=goodz-gke-cicd-pipeline --region=asia-southeast2 --skaffold-file=skaffold.yml

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GAR_LOCATION: asia-southeast2
  _SERVICE: goodz-backend
  _SECRET_SERVICE: secret-injector
