services:
    backend-app:
        container_name: goodz-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
    prometheus:
        image: prom/prometheus:v2.45.6
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./observability/prometheus/alerting-rules.yml:/etc/prometheus/alerting-rules.yml
    grafana:
        image: grafana/grafana:9.5.20
        container_name: grafana
        ports:
            - "3000:3000"
        restart: unless-stopped
        volumes:
            - ./observability/grafana/provisioning:/etc/grafana/provisioning
    alertmanager:
        image: bitnami/alertmanager:latest
        ports:
            - 9093:9093
        volumes:
            - ./observability/alert-manager/email-alert.yml:/opt/bitnami/alertmanager/conf/config.yml
    mailhog:
        image: mailhog/mailhog:v1.0.1
        ports:
            - 1025:1025
            - 8025:8025