services:
    backend-app:
        container_name: goodz-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
    prometheus:
        image: prom/prometheus:v2.45.6
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    grafana:
        image: grafana/grafana:9.5.20
        container_name: grafana
        ports:
            - "3000:3000"
        restart: unless-stopped
        volumes:
            - ./observability/grafana/provisioning:/etc/grafana/provisioning