server:
  port: ${APP_PORT}
spring:
  application:
    name: goodz-ddd-application
  ## Spring datasource config
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: ["prometheus", "health"]